### ISSUE TITLE
swagger compatibility

### ISSUE THREAD

**Issue by billingb** [siemens/restapidoc#11]
Is this compatible with swagger? Does it produce swagger json that can be consumed by a swagger client? Or is this based on but different? 

How much work would it take to make this swagger complient?

**Comment by aruizca** [comment]
I was also mislead by the project description. I though it was generating Swagger compliant JSON documentation.Pity :-)

**Comment by muenchhausen** [comment]
Thanks for your remark. I started to clarify this in the README as a first step. You are right this would be a nice extension - feel free to enhance it :)
