### ISSUE TITLE
IOException error encountered during startup

### ISSUE THREAD

**Issue by BeckyBecs** [siemens/restapidoc#13]
Hi,

Can you please help with the problem I am encountering?
Basically, I did a `git clone` of the `restapidoc` project in my local machine.
The project is using grails 2.4.4:

```
grails -version
Grails version: 2.4.4
```

I executed `grails test-app --echoOut` and all tests passed.
However, when I execute `grails run-app --verbose`, I get the following error:

```
| Running Grails application
| Error 2015-04-17 16:38:54,131 [localhost-startStop-1] ERROR context.ContextLoader  - Context initialization failed

org.springframework.beans.factory.BeanDefinitionStoreException: IOException parsing XML document from ServletContext resource [/WEB-INF/applicationContext.xml]; nested exception is java.io.FileNotFoundException: Could not open ServletContext resource [/WEB-INF/applicationContext.xml]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:343)
```

**Comment by muenchhausen** [comment]
restapidoc is a plugin without an Grails application. Some time ago, I created a simple sample application that uses restapidoc for documenting a sample with a PetController and  TaxonSpeciesController. This you can start with 'grails run-app'. See https://github.com/muenchhausen/HalTest .
