### ISSUE TITLE
Is there any repository?

### ISSUE THREAD

**Issue by gilboss** [siemens/restapidoc#15]
When i add  compile ":restapidoc:0.1.4"  as gradle dependency the project cannot download the pluggin, doesnt exist a repository

**Comment by muenchhausen** [comment]
which Grails version did you try? Travis builds the sample fine - see https://github.com/muenchhausen/HalTest

**Comment by gilboss** [comment]
Im trying 3.0.8 grails version

**Comment by muenchhausen** [comment]
Grails 3.x is quite different from Grails 2.4. Not just the plugin repository changed. A migration is not planned from my side.
